[package]
name = "modcache"
version = "0.1.0"
authors = ["C J Silverio <ceejceej@gmail.com>"]
edition = "2018"
description = "Tools for making a local searchable database of the Nexus mod list for a moddable game."
readme = "README.md"
license = "BlueOak-1.0.0"
categories = ["command-line-utilities", "games", "nexusmods"]

[dependencies]
anyhow = "1.0.42"
async-std = "1.9.0"
chrono = "0.4.19"
dotenv = "0.15.0"
kv = { version = "0.22.0", features = ["json-value"]}
log = "0.4.14"
loggerv = "0.7.2"
owo-colors = "2.0.0"
prettytable-rs = "0.8.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
ureq = { version="2.1.1", features= ["json"] }
